nmc/nmc/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('representatives.urls')),
]

nmc/representatives/urls.py
from django.urls import path
from . import views
from .views import add_representative, get_wards, manage_counties, manage_wards
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name='index'),
    path('add/', views.add_representative, name='add_representative'),
    path('list/', views.representative_list, name='representative_list'),
    path('table/', views.representative_table, name='representative_table'),
    path('export/', views.export_representatives_csv, name='export_representatives_csv'),
    path('edit_positions/', views.edit_positions, name='edit_positions'),
    path('wards/<int:county_id>/', get_wards, name='get_wards'),
    path('manage-counties/', manage_counties, name='manage_counties'),
    path('manage-wards/<int:county_id>/', manage_wards, name='manage_wards'),
    path('noveu/', views.noveu, name='noveu'),
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

nmc/representatives/models.py
from django.db import models


class County(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Ward(models.Model):
    name = models.CharField(max_length=100)
    county = models.ForeignKey(County, on_delete=models.CASCADE, related_name='wards')

    def __str__(self):
        return self.name


class Position(models.Model):
    title = models.CharField(max_length=100)

    def __str__(self):
        return self.title


class Representative(models.Model):
    name = models.CharField(max_length=100)
    ward = models.ForeignKey(Ward, on_delete=models.CASCADE)
    position = models.ForeignKey(Position, on_delete=models.CASCADE)
    phone_number = models.CharField(max_length=15)
    id_number = models.CharField(max_length=20)
    photo = models.ImageField(upload_to='photos/')

    def __str__(self):
        return self.name

nmc/representatives/forms.py
from django import forms
from .models import Representative, County, Ward


class RepresentativeForm(forms.ModelForm):
    class Meta:
        model = Representative
        fields = ['photo', 'name', 'id_number', 'phone_number', 'ward', 'position']

    county = forms.ModelChoiceField(queryset=County.objects.all(), required=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if 'county' in self.data:
            try:
                county_id = int(self.data.get('county'))
                self.fields['ward'].queryset = Ward.objects.filter(county_id=county_id).order_by('name')
            except (ValueError, TypeError):
                pass  # Invalid input from the client; ignore and fallback to empty Ward queryset
        elif self.instance.pk:
            self.fields['ward'].queryset = self.instance.county.wards.order_by('name')
        else:
            self.fields['ward'].queryset = Ward.objects.none()


class CountyForm(forms.ModelForm):
    class Meta:
        model = County
        fields = ['name']


class WardForm(forms.ModelForm):
    class Meta:
        model = Ward
        fields = ['name']

nmc/representatives/views.py
from django.shortcuts import render, redirect
from .models import Representative, Ward, Position, County
from .forms import RepresentativeForm, CountyForm, WardForm
from django.http import HttpResponse
from django.http import JsonResponse
from django.db.models import Prefetch
from itertools import groupby
from operator import attrgetter
import csv


def index(request):
    return render(request, 'index.html')


def noveu(request):
    return render(request, 'noveu.html')


def add_representative(request):
    if request.method == 'POST':
        form = RepresentativeForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('index')
    else:
        form = RepresentativeForm()
    return render(request, 'add_representative.html', {'form': form, 'counties': County.objects.all()})


def representative_list(request):
    representatives = Representative.objects.select_related('ward', 'position').order_by('ward__name', 'name')
    grouped_representatives = {}
    for ward, group in groupby(representatives, key=attrgetter('ward')):
        grouped_representatives[ward] = list(group)
    return render(request, 'representative_list.html', {'grouped_representatives': grouped_representatives})


def representative_table(request):
    representatives = Representative.objects.all()
    return render(request, 'representative_table.html', {'representatives': representatives})


def edit_positions(request):
    positions = Position.objects.all()
    if request.method == 'POST':
        new_position = request.POST.get('new_position')
        if new_position:
            Position.objects.create(title=new_position)
        positions_to_delete = request.POST.getlist('positions_to_delete')
        Position.objects.filter(id__in=positions_to_delete).delete()
    return render(request, 'edit_positions.html', {'positions': positions})


def export_representatives_csv(request):
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="representatives.csv"'

    writer = csv.writer(response)
    writer.writerow(['Name', 'Ward', 'Position', 'Phone Number', 'ID Number'])

    representatives = Representative.objects.all()
    for representative in representatives:
        writer.writerow(
            [representative.name, representative.ward.name, representative.position.title, representative.phone_number,
             representative.id_number])

    return response


def export_representatives_csv(request):
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="representatives.csv"'

    writer = csv.writer(response)
    writer.writerow(['Name', 'Ward', 'Position', 'Phone Number', 'ID Number'])

    representatives = Representative.objects.all()
    for representative in representatives:
        writer.writerow(
            [representative.name, representative.ward.name, representative.position.title, representative.phone_number,
             representative.id_number])

    return response


def get_wards(request, county_id):
    wards = Ward.objects.filter(county_id=county_id).values('id', 'name')
    return JsonResponse(list(wards), safe=False)


def manage_counties(request):
    counties = County.objects.all()
    if request.method == 'POST':
        form = CountyForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('manage_counties')
    else:
        form = CountyForm()
    return render(request, 'manage_counties.html', {'counties': counties, 'form': form})


def manage_wards(request, county_id):
    county = County.objects.get(id=county_id)
    wards = Ward.objects.filter(county=county)
    if request.method == 'POST':
        form = WardForm(request.POST)
        if form.is_valid():
            ward = form.save(commit=False)
            ward.county = county
            ward.save()
            return redirect('manage_wards', county_id=county.id)
    else:
        form = WardForm()
    return render(request, 'manage_wards.html', {'wards': wards, 'form': form, 'county': county})

nmc/representatives/templates/add_representative.html
{% extends 'base.html' %}

{% block content %}
<h1>Add Representative</h1>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <label>Upload Photo:</label>
    {{ form.photo }} <br>
    
    <label>Name:</label>
    {{ form.name }} <br>
    
    <label>ID Number:</label>
    {{ form.id_number }} <br>
    
    <label>Phone Number:</label>
    {{ form.phone_number }} <br>
    
    <label>Position:</label>
    {{ form.position }} <br>
    
    <label for="id_county">County:</label>
    {{ form.county }} <br>
    
    <label for="id_ward">Ward:</label>
    {{ form.ward }} <br>

    <button type="submit">Submit</button>
</form>

<script>
document.getElementById('id_county').addEventListener('change', function() {
    var countyId = this.value;
    var wardSelect = document.getElementById('id_ward');

    fetch(`/wards/${countyId}/`)
        .then(response => response.json())
        .then(data => {
            wardSelect.innerHTML = '';
            data.forEach(function(ward) {
                var option = new Option(ward.name, ward.id);
                wardSelect.add(option);
            });
        });
});
</script>
{% endblock %}

nmc/representatives/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Representative Management</title>
    {% load static %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'index' %}">Home</a>
        <div class="collapse navbar-collapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'add_representative' %}">Add Representative</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'representative_list' %}">Representative List</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'representative_table' %}">Representative Table</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'edit_positions' %}">Edit Positions</a>
                </li>
            </ul>
        </div>
    </nav>
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

nmc/representatives/templates/edit_positions.html
{% extends 'base.html' %}

{% block content %}
<h1>Edit Positions</h1>
<form method="post">
    {% csrf_token %}
    <div class="form-group">
        <label for="new_position">New Position</label>
        <input type="text" class="form-control" id="new_position" name="new_position" placeholder="Enter new position">
    </div>
    <button type="submit" class="btn btn-primary">Add Position</button>
</form>
<hr>
<h2>Existing Positions</h2>
<form method="post">
    {% csrf_token %}
    <ul class="list-group">
        {% for position in positions %}
        <li class="list-group-item">
            <input type="checkbox" name="positions_to_delete" value="{{ position.id }}"> {{ position.title }}
        </li>
        {% endfor %}
    </ul>
    <button type="submit" class="btn btn-danger mt-3">Delete Selected</button>
</form>
{% endblock %}

nmc/representatives/templates/index - Copy.html
{% extends 'base.html' %}

{% block content %}
<h1>Choropleth Map of Kenya</h1>
<div id="map" style="height: 500px;"></div>
<script src="https://unpkg.com/leaflet/dist/leaflet.js"></script>
<script>
    var map = L.map('map').setView([-1.286389, 36.817223], 6);

    L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
        attribution: '&copy; OpenStreetMap contributors'
    }).addTo(map);

    // Load GeoJSON data and add to map
    // This is just a placeholder, replace with your actual GeoJSON data URL
    fetch('/static/kenya_wards.geojson')
        .then(response => response.json())
        .then(data => {
            L.geoJSON(data, {
                style: function(feature) {
                    return {
                        color: 'white',
                        fillColor: feature.properties.hasRepresentative ? 'green' : 'red',
                        fillOpacity: 0.7
                    };
                }
            }).addTo(map);
        });
</script>
{% endblock %}

nmc/representatives/templates/index.html
{% extends 'base.html' %}

{% block content %}
<h1>National MCA Caucus Leadership: Sub- County</h1>

<div style="min-height:823px" id="datawrapper-vis-1ACSm"><script type="text/javascript" defer src="https://datawrapper.dwcdn.net/1ACSm/embed.js" charset="utf-8" data-target="#datawrapper-vis-1ACSm"></script><noscript><img src="https://datawrapper.dwcdn.net/1ACSm/full.png" alt="" /></noscript></div>

{% endblock %}

nmc/representatives/templates/manage_counties.html
{% extends 'base.html' %}

{% block content %}
<h1>Manage Counties</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Add County</button>
</form>

<ul>
    {% for county in counties %}
        <li>{{ county.name }}</li>
        <a href="{% url 'manage_wards' county.id %}">Manage Wards</a>
    {% endfor %}
</ul>
{% endblock %}

nmc/representatives/templates/manage_wards.html
{% extends 'base.html' %}

{% block content %}
<h1>Manage Wards for {{ county.name }}</h1>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Add Ward</button>
</form>

<ul>
    {% for ward in wards %}
        <li>{{ ward.name }}</li>
        <!-- You can add options for editing or deleting wards here -->
    {% endfor %}
</ul>

<a href="{% url 'manage_counties' %}">Back to Counties</a>
{% endblock %}

nmc/representatives/templates/representative_list.html
<!DOCTYPE html>
<html lang="en">

    <!-- Basic -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">   
   
    <!-- Mobile Metas -->
    <meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
 
     <!-- Site Metas -->
    <title>Representative List | National MCA Caucus- Learn. Empower. Inform</title>  
    <meta name="keywords" content="">
    <meta name="description" content="">
    <meta name="author" content="">

    {% load static %}

    <!-- Site Icons -->
    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon" />
    <link rel="apple-touch-icon" href="{% static 'images/apple-touch-icon.png' %}">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <!-- Site CSS -->
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <!-- Colors CSS -->
    
    <!-- ALL VERSION CSS -->
    <link rel="stylesheet" href="{% static 'css/versions.css' %}">
    <!-- Responsive CSS -->
    <link rel="stylesheet" href="{% static 'css/responsive.css' %}">
    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">

    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>
<body class="politics_version">

    <!-- LOADER -->
    <div id="preloader">
        <div id="main-ld">
			<div id="loader"></div>  
		</div>
    </div><!-- end loader -->
    <!-- END LOADER -->

    <div class="topbar text-center hidden-xs">
        <p>Address: The Base Building, P.O Box: 123 Nairobi, Kenya. | Phone Number: 0712337845</p>
    </div>

    <header class="header header_style_01">
        <nav class="megamenu navbar navbar-default">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="index.html"><img src="{% static 'images/logos/logo.png' %}" alt="image"></a>
                </div>
                <div id="navbar" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav navbar-right">
                        <li><a data-scroll-nav="0" href="#main-banner" class="active">Home</a></li>
                        <li><a data-scroll-nav="1" href="#about">About Us</a></li>
                        <li><a data-scroll-nav="2" href="#map">Map</a></li>
                        <li><a data-scroll-nav="3" href="#representatives">Our Representatives</a></li>
                        <li><a data-scroll-nav="4" href="#contact">Contact</a></li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
	
	
	

<div id="event" class="section wb" scroll-index="3">
    <div class="container">

        <div class="section-title text-center">
                <h3>Our Representatives</h3>
                <p class="lead">Membership in the National MCA Caucus is open to all elected MCAs in Kenya. By joining, you will gain access to a wealth of resources, support, and a community of like-minded leaders dedicated to improving the lives of their constituents.</p>
            </div><hr><!-- end title -->

        {% for ward, representatives in grouped_representatives.items %}
            <div class="section-title text-center">
                <h3>{{ ward.name }}</h3>
            </div>
            
            <div class="row">
                {% for representative in representatives %}
                    <div class="col-md-4">
                        <div class="participate-wrap">
                            <img src="{{ representative.photo.url }}" alt="{{ representative.name }}" class="img-responsive" width="80" height="80">
                            <div class="event_dit">
                                <h4>{{ representative.name }}</h4>
                                <ul>
                                    <li><i class="fa fa-user-circle"></i> Position: {{ representative.position.title }}</li><br><br>
                                    <li><i class="fa fa-map-marker"></i> Ward: {{ representative.ward.name }}</li>
                                </ul>
                                
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div><br><hr><br>
        {% endfor %}
    </div>
</div>


    <div id="donate" data-scroll-index="4" class="section db">
        <div class="container">
            <div class="section-title text-center">
                <h3>Contact Us</h3>
                <p class="lead">Stay informed about our activities, upcoming events, and initiatives. Follow us on social media and participate in our forums to make your voice heard.</p>
            </div><!-- end title -->

            <div class="row">
                <div class="col-md-12">
                    <div class="contact_form">
                        <div id="message"></div>
                        <form id="contactform" class="row" action="contact.php" name="contactform" method="post">
                            <fieldset class="row-fluid">
                                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                    <input type="text" name="first_name" id="first_name" class="form-control" placeholder="First Name">
                                </div>
                                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                    <input type="text" name="last_name" id="last_name" class="form-control" placeholder="Last Name">
                                </div>
                                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                    <input type="email" name="email" id="email" class="form-control" placeholder="Your Email">
                                </div>
                                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                    <input type="text" name="phone" id="phone" class="form-control" placeholder="Your Phone">
                                </div>
                                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                    <label class="sr-only">Select Service</label>
                                    <select name="select_service" id="select_service" class="selectpicker form-control" data-style="btn-white">
                                        <option value="12">Donate For?</option>
                                        <option value="Political Parties">Political Parties</option>
                                        <option value="For Politician">For Politician</option>
                                        <option value="Others">Others</option>
                                    </select>
                                </div>
                                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                    <label class="sr-only">What is max price?</label>
                                    <select name="select_price" id="select_price" class="selectpicker form-control" data-style="btn-white">
                                        <option value="$100 - $2000">Sh. 10 - Sh. 100</option>
                                        <option value="$2000 - $4000">Sh. 100 - Sh. 1000</option>
                                        <option value="$4000 - $10000">Sh. 1000 - Sh. 10000</option>
                                    </select>
                                </div>
                                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                    <textarea class="form-control" name="comments" id="comments" rows="6" placeholder="Why you are donating to us?"></textarea>
                                </div>
                                <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12 text-center">
                                    <button type="submit" value="SEND" id="submit" class="btn btn-light btn-radius btn-brd grd1 btn-block">Pay Now via PayPal</button>
                                </div>
                            </fieldset>
                        </form>
                    </div>
                </div><!-- end col -->
            </div><!-- end row -->
        </div><!-- end container -->
    </div><!-- end section -->

    <div class="copyrights">
        <div class="container">
            <div class="footer-distributed">
                <div class="footer-left">
                    <p class="footer-links">
                        <a href="#main-banner">Home</a>
                        <a href="#about">About Us</a>
                        <a href="#map">Map</a>
                        <a href="#representatives">Our Representatives</a>
                        <a href="#donate">Contact Us</a>
                    </p>
                    <p class="footer-company-name">All Rights Reserved. &copy; 2024 , National MCA Caucus | GitHub : 
					<a href="https://github.com/bwanatemba">bwanatemba</a></p>
                </div>

                <div class="footer-right">
                    <form method="get" action="#">
                        <input placeholder="Subscribe our newsletter.." name="search">
                        <i class="fa fa-envelope-o"></i>
                    </form>
                </div>
            </div>
        </div><!-- end container -->
    </div><!-- end copyrights -->

    <a href="#" id="scroll-to-top" class="dmtop global-radius"><i class="fa fa-angle-up"></i></a>

    <!-- ALL JS FILES -->
    <script src="{% static 'js/all.js' %}"></script>
	<!-- Camera Slider -->
	<script src="{% static 'js/jquery.mobile.customized.min.js' %}"></script>
	<script src="{% static 'js/jquery.easing.1.3.js' %}"></script> 
	<script src="{% static 'js/camera.min.js' %}"></script>
	<script src="{% static 'js/scrollIt.min.js' %}"></script>
    <!-- ALL PLUGINS -->
    <script src="{% static 'js/custom.js' %}"></script>
    <script src="{% static 'js/jquery.vide.js' %}"></script>

</body>
</html>

nmc/representatives/templates/representative_table.html
{% extends 'base.html' %}

{% block content %}
<h1>Representative Table</h1>
<table class="table">
    <thead>
        <tr>
            <th>Name</th>
            <th>Ward</th>
            <th>Position</th>
            <th>Phone Number</th>
            <th>ID Number</th>
        </tr>
    </thead>
    <tbody>
        {% for representative in representatives %}
        <tr>
            <td>{{ representative.name }}</td>
            <td>{{ representative.ward.name }}</td>
            <td>{{ representative.position.title }}</td>
            <td>{{ representative.phone_number }}</td>
            <td>{{ representative.id_number }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
<a href="{% url 'export_representatives_csv' %}" class="btn btn-primary">Export as CSV</a>
{% endblock %}

nmc/representatives/templates/representativelist2.html
{% extends 'base.html' %}
{% block content %}

<h1>Representative List</h1>

{% for ward, representatives in grouped_representatives.items %}
    <h2>{{ ward.name }}</h2>
    {% for representative in representatives %}
        <div class="card mb-3">
            <div class="row no-gutters">
                <div class="col-md-4">
                    <img src="{{ representative.photo.url }}" class="card-img" alt="{{ representative.name }}">
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <h5 class="card-title">{{ representative.name }}</h5>
                        <p class="card-text">Position: {{ representative.position.title }}</p>
                        <p class="card-text">Ward: {{ representative.ward.name }}</p>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
{% endfor %}

{% endblock %}